# Supabase local / GitHub integration config.
# https://supabase.com/docs/guides/deployment/branching/github-integration

project_id = "luyeytfhofbmhwnjfeaa"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
